---

- hosts: all
  become: true 
  tasks:

  - name: intall apache and lib packege + update 
    package: 
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

