---

- hosts: all
  become: true 
  pre_tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: intall apache and lib packege + update 
    tags: web_server, test, tags
    package: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
      
  - name: install mariaDB 
    tags: mariadb, test, tags
    package:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
